In [34]:
import numpy as np
import pandas as pd

# Load the Dataset

In [35]:
df = pd.read_csv("../data/gdp_data.csv")

In [36]:
# Quick preview of the dataset
df.head()

                       country country_code  Year  GDP_Billions
0  Africa Eastern and Southern          AFE  2025   1358.694051
1  Africa Eastern and Southern          AFE  2024   1252.564135
2  Africa Eastern and Southern          AFE  2023   1179.121536
3  Africa Eastern and Southern          AFE  2022   1226.461319
4  Africa Eastern and Southern          AFE  2021   1113.059797

In [37]:
df[df["country"] == "Ghana"].head()

     country country_code  Year  GDP_Billions
8052   Ghana          GHA  2025    114.209905
8053   Ghana          GHA  2024     83.288586
8054   Ghana          GHA  2023     80.547147
8055   Ghana          GHA  2022     73.919003
8056   Ghana          GHA  2021     79.514205

In [38]:
# Check Dataframe shape(rows, columns)
print(f"Dataset shape: {df.shape}")

#Check column data types and non-null counts
df.info()

#Summary statistics for numerical features
df.describe()

Dataset shape: (17490, 4)
<class 'pandas.DataFrame'>
RangeIndex: 17490 entries, 0 to 17489
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       17490 non-null  str
 1   country_code  17490 non-null  str
 2   Year          17490 non-null  int64
 3   GDP_Billions  14745 non-null  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 546.7 KB

               Year   GDP_Billions
count  17490.000000   14745.000000
mean    1992.500000    1283.475494
std       19.050916    5945.520551
min     1960.000000       0.002586
25%     1976.000000       2.393650
50%     1992.500000      17.856393
75%     2009.000000     209.691946
max     2025.000000  118350.166039

# Question 1: How many unique entities (countries/aggregates) are in the dataset?

In [39]:
total_entities = df["country"].nunique()
print(f"Total unique country/regional entries: {total_entities}")

Total unique country/regional entries: 265

# Question 2: What is the range of years covered in the dataset?

In [40]:
min_year = int(df["Year"].min())
max_year = int(df["Year"].max())
print(f"Earliest year: {min_year}")
print(f"Latest year: {max_year}")
print(f"Total span: {max_year - min_year + 1} years")

Earliest year: 1960
Latest year: 2025
Total span: 66 years

# Question 3: How much missing data (null values) exists?

In [44]:
missing_df = pd.DataFrame({"Missing Values": df.isnull().sum(), "Percentage (%)": (df.isnull().mean() * 100).round(2),})
missing_df

              Missing Values  Percentage (%)
country                    0            0.00
country_code               0            0.00
Year                       0            0.00
GDP_Billions            2745           15.69

# Question 4: Top Economies in the Latest Available Year

In [47]:
latest_year = int(df["Year"].max())
df_latest = df[(df["Year"] == latest_year) & (df["GDP_Billions"].notnull())]

#Show top 10 entities by GDP
top_10 = df_latest.sort_values(by="GDP_Billions", ascending=False).head(10)
top_10[["country", "country_code", "Year", "GDP_Billions"]]

                        country country_code  Year   GDP_Billions
3102                      World          WLD  2025  118350.166039
990                 High income           XD  2025   76878.050748
2310               OECD members          OED  2025   72543.267888
2508  Post-demographic dividend          PST  2025   67379.697065
1122           IDA & IBRD total          IBT  2025   46251.403469
1056                  IBRD only          IBD  2025   43056.359079
1716        Low & middle income          LMY  2025   41478.597585
2112              Middle income          MIC  2025   40836.798203
396         East Asia & Pacific          EAS  2025   33656.980597
3036        Upper middle income           XT  2025   33529.653864